--CREATE TABLE club_chairs (
--  user INTEGER REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
--  club INTEGER REFERENCES clubs ON DELETE RESTRICT ON UPDATE CASCADE,
--  is_approved INTEGER NOT NULL DEFAULT FALSE,
--  PRIMARY KEY (user, club)
--) STRICT;

